### ISSUE TITLE
itunes

### ISSUE THREAD

**Issue by PANOSSS1980** [iWeya/tune-search#2]
MY FRIEND PLEASEEEEEEEE CAN YOU MAKE A WEB VERSION?I HAVE NO IDEA FROM DEVELOPING AND I DONT KNOW HOW TO DO IT!!!I AM BEGGING YOU MAN

**Comment by iWeya** [comment]
Hi, friend. This project already is a web application. If you want to run it, you can clone the repository, open it in terminal and follow the steps described in the [README.md](https://github.com/iWeya/tune-search/blob/master/README.md) file:

``` bash
> npm install
> npm run serve
```

I hope this helps you.

**Comment by PANOSSS1980** [comment]
WOOWWWWWWW MY FRIEND I HAVE NO IDEA HOW TO DO IT!!!CAN YOU TELL ME ALL THE STEPS OR MUCH BETTER CAN WE USE TEAMVIWER TO HELP ME???

**Comment by PANOSSS1980** [comment]
PLEASE MAN...CAN YOU HELP ME???

**Comment by iWeya** [comment]
> 
> 
> WOOWWWWWWW MY FRIEND I HAVE NO IDEA HOW TO DO IT!!!CAN YOU TELL ME ALL THE STEPS OR MUCH BETTER CAN WE USE TEAMVIEWER TO HELP ME???

If these steps do not make sense to you, I suggest you study about web development. Soon you will be able of run this project locally or even deploy it.
I appreciate this thread on Reddit, that presents a list of good start points to learn web development:
https://www.reddit.com/r/webdev/comments/7ngwz7/where_to_start_to_learn_web_development/

I hope this helps you.
